[project]
name = "osu-beatmap-to-mania-converter"
version = "v0.3.0"
requires-python = ">= 3.12"
description = "Convert OSU! beatmap to OSU!Mania."
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["osu", "game", "windows", "rhythm", "beatmap"]
